version: '24.0.5'

services:
  db:
    image: postgres:15.0-alpine
    ports:
      - 8888:5432 # - 5432:5432
    env_file:
      - ./.env

#  web:
#    build: .
#    volumes:
#      - .:/app
#    ports:
#      - 8000:8000
#    env_file:
#      - ./.env
#    depends_on:
#      - db
#    command: python3 server.py