version: '24.0.5'


services:
  db:
    image: postgres:15.0-alpine
    ports:
      - 5431:5432 # - 5432:5432
    env_file:
      - ./.env
    networks:
      app_network:
        aliases:
          - ${POSTGRES_HOST}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    command: python3 server.py
    networks:
      - app_network

networks:
  app_network: